swagger: "2.0"
info:
  version: ""
  title: "Swagger zukaishi todolist"
tags:
- name: "todolist"
  description: "todo取得"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "todo"
  description: "todo更新"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /todolist:
    post:
      tags:
        - "todolist"
      summary: "todolist取得"
      description: ""
      operationId: "todolist"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/TodoList"
      responses:
        default:
          description: "successful operation"
  /todo:
    post:
      tags:
        - "todo"
      summary: "todoを追加する"
      description: ""
      operationId: "todoadd"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/TodoAdd"
      responses:
        default:
          description: "successful operation"
    put:
      tags:
        - "todo"
      summary: "todoを修正する"
      description: ""
      operationId: "todoupd"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/TodoUpd"
      responses:
        default:
          description: "successful operation"
    delete:
      tags:
        - "todo"
      summary: "todoを削除する"
      description: ""
      operationId: "tododel"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/TodoDel"
      responses:
        default:
          description: "successful operation"
definitions:
  TodoList:
    type: "object"
    properties:
      mid:
        type: "string"
      routine_flag:
        type: "integer"
        format: "int64"
    xml:
      name: "TodoList"
  TodoAdd:
    type: "object"
    properties:
      mid:
        type: "string"
      routine_flag:
        type: "integer"
        format: "int64"
    xml:
      name: "TodoAdd"
  TodoUpd:
    type: "object"
    properties:
      mid:
        type: "string"
      routine_flag:
        type: "integer"
        format: "int64"
    xml:
      name: "TodoUpd"
  TodoDel:
    type: "object"
    properties:
      mid:
        type: "string"
      routine_flag:
        type: "integer"
        format: "int64"
    xml:
      name: "TodoDel"
